name: flutter_roster
description: Roster widget with an underlying timetable included
version: 0.0.1
homepage: https://github.com/Iconica-Development/flutter_roster

publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_date_time_picker:
    git:
      url: git@github.com:Iconica-Development/flutter_date_time_picker.git
      ref: stable
  timetable:
    git:
      url: git@github.com:Iconica-Development/timetable.git
      ref: v0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
