name: flutter_roster
description: Roster widget with an underlying timetable included
version: 2.3.0
homepage: https://github.com/Iconica-Development/flutter_roster

publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_date_time_picker:
    git:
      url: https://github.com/Iconica-Development/flutter_date_time_picker
      ref: 3.3.3
  flutter_timetable:
    git:
      url: https://github.com/Iconica-Development/flutter_timetable
      ref: 1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
